### ISSUE TITLE
LogFilter generates malformed X-B3-TraceId; X-B3-SpanId is missing

### ISSUE THREAD

**Issue by sabertiger** [predix/spring-log-filter#8]
LogFilter is generating `X-B3-TraceId` as an UUID (ie ce0085cc-ea90-41f9-938a-82fdf5394637) instead of 128 or 64 bit hex string and is missing a required field `X-B3-SpanId`.

This results in java.lang.IllegalArgumentException when parsing from conforming clients such as spring-cloud-sleuth.
```
Exception occurred while trying to extract span from carrier: Malformed id: ce0085cc-ea90-41f9-938a-82fdf5394637
```

According to the [Zipkins doc](http://zipkin.io/pages/instrumenting.html):

HTTP Tracing
HTTP headers are used to pass along trace information.
The B3 portion of the header is so named for the original name of Zipkin: BigBrotherBird.
Ids are encoded as hex strings:

X-B3-TraceId: 128 or 64 lower-hex encoded bits (required)
X-B3-SpanId: 64 lower-hex encoded bits (required)

**Comment by sanjeevchopra** [comment]
traceid generation needs to be most likely removed , as noted in https://github.com/predix/spring-log-filter/issues/9

**Comment by metacubed** [comment]
The functionality to generate trace and span ids has been removed from the latest release.

OpenTracing/Brave now defines three separate standards for tracing headers, so it's best to rely on their standard libraries for detection/generation of these values.
